export default [
    {
        id: '1',
        poster_firstName: 'Hunter',
        poster_lastName: 'Kim',
        date_posted: '02-03-2020 11:03 AM',
        title: 'Paint Night',
        text: 'Hey everyone, I will be attending Paint Night I hope you everyone can attend. RSVP at www.respond.com',
        photoUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/university-paint-night-event-flyer-design-template-be72bff9c44b5850916ba3d4971f28d4_screen.jpg?ts=1561414684',
    },
    {
        id: '2',
        poster_firstName: 'Ryan',
        poster_lastName: 'Assint',
        date_posted: '01-03-2020 01:40 AM',
        title: 'Basketball Tournament',
        text: 'Residents lets support our team tonight. Remember no entrance fee for students 😁', 
        photoUrl: 'https://i.pinimg.com/736x/c8/9e/4d/c89e4d62d6736d360a2ded9aa9b26527.jpg',
    },
    {
        id: '3',
        poster_firstName: 'Ron',
        poster_lastName: 'Art',
        date_posted: '01-05-2020 11:03 PM',
        title: 'Remixing Pop Culture',
        text: 'If anyone is interested I will be hosting a Remixing Pop Culture event with my student organization', 
        photoUrl: 'https://femfreq2.files.wordpress.com/2010/02/remixing-pop-culture1.jpg',
    },
    {
        id: '4',
        poster_firstName: 'Hunter',
        poster_lastName: 'Kim',
        date_posted: '02-03-2020 11:03 AM',
        title: 'Paint Night',
        text: 'Hey everyone, I will be attending Paint Night I hope you everyone can attend. RSVP at www.respond.com',
        photoUrl: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/university-paint-night-event-flyer-design-template-be72bff9c44b5850916ba3d4971f28d4_screen.jpg?ts=1561414684',
    },
    {
        id: '5',
        poster_firstName: 'Ryan',
        poster_lastName: 'Assint',
        date_posted: '01-03-2020 01:40 AM',
        title: 'Basketball Tournament',
        text: 'Residents lets support our team tonight. Remember no entrance fee for students 😁', 
        photoUrl: 'https://i.pinimg.com/736x/c8/9e/4d/c89e4d62d6736d360a2ded9aa9b26527.jpg',
    },
    {
        id: '6',
        poster_firstName: 'Ron',
        poster_lastName: 'Art',
        date_posted: '02-03-2020 11:03 AM',
        title: 'Remixing Pop Culture',
        text: 'If anyone is interested I will be hosting a Remixing Pop Culture event with my student organization', 
        photoUrl: 'https://femfreq2.files.wordpress.com/2010/02/remixing-pop-culture1.jpg',
    }
];